### ISSUE TITLE
More planar graph samples?

### ISSUE THREAD

**Issue by arianaa30** [bsmock/k-shortest-paths#1]
Hi,
Thanks for the implementation. It was the most easy to use source I found.
Do you happen to have more of those graph sample files? How can I find a bunch of them given your input format? I'm interested in bigger road networks. I would like to see how your implementation's runtime is.
Thanks.

**Comment by bsmock** [comment]
Hi,

I would consider adding more example data to the repository but this might not happen right away.

If you need more data soon, I'd suggest trying here: [http://www.dis.uniroma1.it/challenge9/download.shtml](http://www.dis.uniroma1.it/challenge9/download.shtml).

It should be pretty straightforward to get the data there into the format used by my implementations.

If all you want is just bigger files to test with, and you don't care what road networks they actually correspond to, you can email me. I should have some bigger files I can send you.

Cheers,
Brandon

**Comment by arianaa30** [comment]
Thanks. I just emailed you with your dr.*** gmail.com email.
