### ISSUE TITLE
What is the license ?

### ISSUE THREAD

**Issue by TomasJohansson** [bsmock/k-shortest-paths#3]
Can you please specify a license for your code "k-shortest-paths" ?
https://choosealicense.com

**Comment by bsmock** [comment]
Thank you, Tomas, for raising this issue.

I released v1.0.1 of the software with GPLv3. I have revisited this and decided to change the license to Apache License 2.0, which is now included as a separate file.

If you have any thoughts or concerns, let me know.

Best,
Brandon
